version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5-stretch
    steps:
      - checkout
      - run: pip install --user -r requirements.txt
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export PATH="/home/circleci/.local/bin:$PATH"' >> $BASH_ENV
      - run: pytest -vv ./test_write.py
